mqtt:
  host: walternate
  port: 1883
  user: "tvsockets"
  password: "o6tdN7lwWpvv"
  topic_prefix: home/livingroom/tvsockets

gpio_modules:
  - name: pcf8574
    module: pcf8574
    i2c_bus_num: 1
    chip_addr: 0x20

digital_inputs: []

digital_outputs:
  - name: iec1
    module: pcf8574
    pin: 0
    on_payload: "ON"
    off_payload: "OFF"
    inverted: yes

  - name: iec2
    module: pcf8574
    pin: 1
    on_payload: "ON"
    off_payload: "OFF"
    inverted: yes

  - name: iec3
    module: pcf8574
    pin: 2
    on_payload: "ON"
    off_payload: "OFF"
    inverted: yes

  - name: iec4
    module: pcf8574
    pin: 3
    on_payload: "ON"
    off_payload: "OFF"
    inverted: yes

  - name: topleft
    module: pcf8574
    pin: 4
    on_payload: "ON"
    off_payload: "OFF"
    inverted: yes

  - name: topright
    module: pcf8574
    pin: 5
    on_payload: "ON"
    off_payload: "OFF"
    inverted: yes

  - name: bottomleft
    module: pcf8574
    pin: 6
    on_payload: "ON"
    off_payload: "OFF"
    inverted: yes

  - name: bottomright
    module: pcf8574
    pin: 7
    on_payload: "ON"
    off_payload: "OFF"
    inverted: yes
