name: MQTT IO CI
on:
  - push
  - pull_request
  - release
jobs:
  test:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        python-version: [3.6, 3.7, 3.8]

    steps:
      - uses: actions/checkout@v2
      - name: Setup Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          pip install poetry
          poetry install
      - name: Lint with pylint
        run: poetry run pylint -d fixme mqtt_io
      - name: Lint with mypy
        run: poetry run mypy --show-error-codes --strict --no-warn-unused-ignores mqtt_io
      - name: Test with behave
        run: poetry run behave -t ~skip mqtt_io/tests/features
  publish:
    name: Publish to PyPI
    if: github.event_name == 'release" && github.event.action == 'created'
    runs-on: ubuntu-20.04
    needs: test
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install poetry
        run: pip install poetry
      - name: Build packages
        run: poetry build
      - name: Publish packages
        uses: pypa/gh-action-pypi-publish@master
        # if: startsWith(github.ref, 'refs/tags')
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}

  generate_docs:
    name: Generate Documentation
    if: github.event_name == 'push'
    concurrency: generate_docs
    runs-on: ubuntu-20.04
    steps:
      - name: Dump Context
        env:
          GH_EVENT: ${{ toJson(github.event) }}
          GH_EVENT_NAME: ${{ github.event_name }}
        run: echo "$GH_EVENT_NAME" && echo "$GH_EVENT"
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - id: branch-name
        uses: tj-actions/branch-names@v2.2
      - name: Ensure we can checkout gh-pages
        run: |
          git checkout gh-pages
          git checkout ${{ steps.branch-name.outputs.current_branch }}
      - name: Setup Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies and generate docs
        run: |
          pip install poetry
          poetry install
          poetry run python docs_src/generate_docs.py
