name: Test and publish
on: push

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        python-version: ["2.7", "3.6", "3.7", "3.8", "3.9"]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - run: pip install black
        if: matrix.python-version != '2.7'
      - run: pip install pytest mock -r requirements.txt
      - run: make schema
      - run: make black
        if: matrix.python-version != '2.7'
      - run: PYTHONPATH=$GITHUB_WORKSPACE py.test -m "not hw_raspberrypi and not mqtt"
  publish:
    name: Publish to PyPI if tagged
    runs-on: ubuntu-18.04
    needs: test
    strategy:
      matrix:
        python-version: ["2.7", "3.6"]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - run: pip install black
        if: matrix.python-version != '2.7'
      - run: pip install -r requirements.txt
      - run: make schema
      - run: make black
        if: matrix.python-version != '2.7'
      - run: pip install build
      - run: python -m build --wheel --outdir dist/ .
        if: matrix.python-version == '2.7'
      - run: python -m build --sdist --wheel --outdir dist/ .
        if: matrix.python-version == '3.6'
      - uses: pypa/gh-action-pypi-publish@master
        if: startsWith(github.ref, 'refs/tags')
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}
